### ISSUE TITLE
A few feature and structural change request

### ISSUE THREAD

**Issue by vxbinaca** [xofred/deviantart-gallery-downloader#1]
- More secure login method, username and PW are in command not good for multi-user systems
- ~/.netrc capability for auth, youtube-dl has this
- Default behavior to mirror albums when sent to main /gallery and organize rips accordingly locally
- Inclusion in gem repository

Great work love the script. Only one that works or isn't crashy. Thank you.

**Comment by xofred** [comment]
@vxbinaca  Thanks for the advice. .netrc seems a good idea. And glad you like it :)

**Comment by xofred** [comment]
@vxbinaca Add feature about ~/.netrc capability for auth. Please check out https://github.com/xofred/deviantart-gallery-downloader/tree/dev

**Comment by vxbinaca** [comment]
Git isn't allowing me to change branches. But, lemme try something I think I may have found a problem not related from this.

**Comment by xofred** [comment]
Already pushed to master branch, closing this issue.
