### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by Efreak** [xofred/deviantart-gallery-downloader#12]
The generated credentials are brand new. I can log in thru the browser using them just fine (I'm unable to test them in other software such as [4pr0n/ripme](https://github.com/4pr0n/ripme) due to changes in DA's website (see 4pr0n/ripme#425); I'm not sure if perhaps this issue is caused by the same changes?

```
[efreak:~/source/deviantart-gallery-downloader] master 17s 1 ± ruby fetch.rb -n http://starkiteckt.deviantart.com/gallery/
Using netrc's credential
Connecting to deviantART
Logging in
undefined method `username=' for nil:NilClass
will retry after 1 second
undefined method `username=' for nil:NilClass
will retry after 1 second
undefined method `username=' for nil:NilClass
will retry after 1 second
undefined method `username=' for nil:NilClass
login failed after 3 retries
You might not be able to fetch the age restricted resources
Connecting to gallery
/home/efreak/source/deviantart-gallery-downloader/lib/deviantart_gallery_downloader.rb:24:in `fetch': undefined method `[]' for nil:NilClass (NoMethodError)
        from fetch.rb:3:in `<main>'
```

**Comment by xofred** [comment]
Fixed, plz pull the newest master branch and try again...

**Comment by nonamethanks** [comment]
Hello, I cloned the latest master and it still returns the same error.
```
Using netrc's credential
Connecting to deviantART
Logging in
Log on successful
Connecting to gallery
/home/nonamethanks/tools/deviantart-gallery-downloader/lib/deviantart_gallery_downloader.rb:23:in `fetch': undefined method `[]' for nil:NilClass (NoMethodError)
	from fetch.rb:3:in `<main>'
```

**Comment by xofred** [comment]
If possible, may you provide the gallery link? Maybe pagination selector is not suited for every gallery...

**Comment by nonamethanks** [comment]
http://oevrlord.deviantart.com/
http://martinhanford1974.deviantart.com/
Really no gallery I've tried works.

**Comment by xofred** [comment]
I've tried http://oevrlord.deviantart.com/gallery/, it works. Remember to use GALLERY's PAGE, not author's page...

**Comment by xofred** [comment]
@nonamethanks Is it ok now? If everything is find, I would like to close this issue.

**Comment by nonamethanks** [comment]
Yes, if I use the /gallery/ url it works @xofred

**Comment by xofred** [comment]
Glad to hear it!

**Comment by vxbinaca** [comment]
Requesting re-open. 

I purged the install of this script, still not working.
Purged my Gems install, still not working.

```ruby fetch.rb -n  http://alexandrab24.deviantart.com/gallery/?catpath=/```

```
Using netrc's credential
Logging in
Log on successful
Connecting to gallery
undefined method `[]' for nil:NilClass
will retry after 1 second
undefined method `[]' for nil:NilClass
will retry after 1 second
undefined method `[]' for nil:NilClass
will retry after 1 second
undefined method `[]' for nil:NilClass
failed to connect to gallery after 3 retries, abort
```

**Comment by xofred** [comment]
Please try `ruby fetch.rb -n http://alexandrab24.deviantart.com/gallery/` instead @vxbinaca

**Comment by vxbinaca** [comment]
Same result.

**Comment by xofred** [comment]
![2017-03-14 3 16 29](https://cloud.githubusercontent.com/assets/2174219/23891403/2b45769c-08d1-11e7-83a1-06ac1b663c46.png)
It has to be gallery's page such as http://alexandrab24.deviantart.com/gallery/, not http://alexandrab24.deviantart.com/ or anything else. @vxbinaca

**Comment by vxbinaca** [comment]
I ran the same command you did and got the same error.

**Comment by xofred** [comment]
@vxbinaca Could you provide the detailed error message, such as error line of code?

**Comment by vxbinaca** [comment]
@xofred ptrace? That's the output I got:

```ruby fetch.rb -n "http://megasweet.deviantart.com/gallery/" ```

```
Logging in
Log on successful
Connecting to gallery
undefined method `[]' for nil:NilClass
will retry after 1 second
undefined method `[]' for nil:NilClass
will retry after 1 second
undefined method `[]' for nil:NilClass
will retry after 1 second
undefined method `[]' for nil:NilClass
failed to connect to gallery after 3 retries, abort
```

**Comment by xofred** [comment]
@vxbinaca Plz check out dev branch, it may solve the issue. And it can provide more error messages if not.

**Comment by 1n5aN1aC** [comment]
I was having the same issue on my debian system, and the dev branch fixed it.

**Comment by 1n5aN1aC** [comment]
EDIT:  It's only fetching the first page (usually around 22 or so) then it thinks it's done.  With or without the "/?catpath=/"

Tested on 4 different user's galleries, same results.

**Comment by xofred** [comment]
Without it. If it still not work, Could you provide the gallery link for me to debug? @1n5aN1aC

**Comment by 1n5aN1aC** [comment]
Well, something like `ruby fetch.rb USERNAME PASSWORD http://sangrde.deviantart.com/gallery/` begins to download, but starts at 1/22, and once it reaches 22/22, it just says "all downloads completed."

I've tried it on 3 other artists' galleries as well, and all of them I've tried so far, either with personal credential, or with -n seem to do the same thing.

**Comment by xofred** [comment]
Turns out to be an account setting issue. Please go to https://www.deviantart.com/settings/browsing. In "**General Browsing**" section, make sure "**Display**" as "**24 Thumbnails per Page**" and "**Paging**" as "**Click through pages**"
![2017-06-19 11 36 58](https://user-images.githubusercontent.com/2174219/27268778-7a0edf0c-54e4-11e7-859c-c7b0b7200a77.png)

**Comment by 1n5aN1aC** [comment]
Ahh, so "scroll through pages" isn't compatible.  Makes sense, even if it is disappointing. 

I'd suggest you add that tidbit to a FAQ somewhere, but it's solved for me!

**Comment by xofred** [comment]
Good point, README updated.

**Comment by vxbinaca** [comment]
Requesting a re-open this has cropped back up, or the open issue might possibly be a fix. Why he diff'd instead of a PR is beyond me.

**Comment by 1n5aN1aC** [comment]
Sadly, can confirm.  As of maybe a little over a week ago, even the dev branch is broken again.
Will provide output text / more information in a couple hours, assuming I don't forget.
