### ISSUE TITLE
Works lovely, but can it download the entire gallery?

### ISSUE THREAD

**Issue by 1n5aN1aC** [xofred/deviantart-gallery-downloader#13]
This is more of a feature request, and feel free to say no, but:

Would it be possible to make the downloader compatible with `/gallery/?catpath=/`?
Under normal circumstances, if you provide it with a gallery URL, it downloads all images in that page.  However, users can also move images into folders, which causes them to no longer show up in that list.  If you go to the URL `/gallery/?catpath=/` then it will however show all images uploaded by that person.

If this is impractical or impossible, I understand.  Just asking because this is the best deviantart archiver I've found, and manually copying in each deviation folder takes a significant portion of time.

**Comment by xofred** [comment]
Pagination logic of gallery with `?catpath=/` is quiet different others.  But as u said, this should be a very useful feature. I may find sometime to work on it. Thx for the advice :)

**Comment by xofred** [comment]
Plz try [dev branch](https://github.com/xofred/deviantart-gallery-downloader/tree/dev). Just provide the gallery link such as http://bluetopaz01.deviantart.com/gallery/, and it should do the trick! @1n5aN1aC

**Comment by 1n5aN1aC** [comment]
Seems to be working!

Thank you very much, this looks to be an amazing update!

I'll let you know if I run into any issues, but it's working great as of now.
