### ISSUE TITLE
Cannot download unless User-Agent is specified

### ISSUE THREAD

**Issue by robertjacobsen** [xofred/deviantart-gallery-downloader#14]
Hi, 

I tried to use the tool to salvage my late DeviantArt account, but was unable to connect to it. After doing some debugging, I discovered that DeviantArt sent out different content to the Mechanize compared to desktop or mobile, but adding the User-Agent header to something desktop-y worked. I was, however, unable to log in, but that might have been a different issue altogether. I didn’t delve more into that, as I did not have any mature/private content I needed to scrape. 

[Here’s the diff](https://gist.github.com/robertjacobsen/b3990d4f17d5c8cb9722a28619bcf2b6) of the changes I did to make the core download work, at least. Note: As I am not a Ruby developer, it’s makeshift and does not follow the [Ruby style guide](https://github.com/bbatsov/ruby-style-guide).

**Comment by vxbinaca** [comment]
@robertjacobsen Please make a PR so we can benefit from this.

**Comment by xofred** [comment]
Thanks for the bug found and solution. Fix is made on the master branch. It's now working again. @robertjacobsen @vxbinaca

**Comment by xofred** [comment]
Close this? @robertjacobsen

**Comment by vxbinaca** [comment]
I vote to close it works for me again.
