### ISSUE TITLE
How can I install it?

### ISSUE THREAD

**Issue by random356** [xofred/deviantart-gallery-downloader#16]
I already have installed bundler, netrc and mechanize but I don't know hot to install this as it isn't a .gem file. Cheers.

**Comment by xofred** [comment]
If u got netrc and mechanize installed, it should be fine to go. 

Just run `ruby fetch.rb [deviantart_username] [deviantart_password] [gallery_url]`

**Comment by xofred** [comment]
And plz get the newest master branch before using, it fixes the login issue @polandball8
