### ISSUE TITLE
Not getting full gallery

### ISSUE THREAD

**Issue by momoe** [xofred/deviantart-gallery-downloader#21]
I've attempted to run the master and the dev branch of this and have had not been getting the full number of  deviations.
for example `ruby fetch.rb -n https://phillip-the-2.deviantart.com/gallery/?catpath=/`

This only downloads the first 12 deviation, while there's 235 currently in the gallery. 

I have set the display to 24 thumb nails and paging to Click through pages. Is there something that needs to be included in the "?catpath=" part of the URL to continue paging?

**Comment by xofred** [comment]
Just /gallery, not including the trailings. See README for the gallery url example

**Comment by momoe** [comment]
I have done `/gallery` the results are the same for that and other deviant galleries. It's failling to grab all the images. The results vary from 10-60% missing

**Update**
Starting to get some positive results, will continue testing and report back

**Update 2** Sucessfully working now after some tweaking. TY for your assistance.
