### ISSUE TITLE
DA not returning login page, maybe use cookies to bypass?

### ISSUE THREAD

**Issue by SecantSystems** [xofred/deviantart-gallery-downloader#23]
As with #15, I'm not able to use the 'log in' feature anymore.  Instead of fetching the login page, dA returns the 'we suspect you're a bot' page (which includes a captcha).  [furaffinity-dl](https://github.com/Shnatsel/furaffinity-dl) uses a cookies.txt file to bypass FA's login page (which also has a captcha), so something like that might work here.  I'm looking right now at another gem by the makers of Mechanize for handling cookies ([http-cookie](https://github.com/sparklemotion/http-cookie)).

**Comment by xofred** [comment]
Login was successful on my end. Since DA has opened its [API](https://www.deviantart.com/developers/), maybe u can try using [them](https://www.deviantart.com/developers/http/v1/20160316)

**Comment by SecantSystems** [comment]
Huh, it works for me again.  Maybe they were experiencing a heavy load just then.  Thanks for the heads-up about the API, I'll look into that going forward.
