### ISSUE TITLE
Not all items gotten on default gallery rip

### ISSUE THREAD

**Issue by vxbinaca** [xofred/deviantart-gallery-downloader#4]
`ruby with_login.rb EMAIL PASSWORD http://s-c.deviantart.com/gallery/`

108 items seen. 84 items end result.

**Comment by xofred** [comment]
@vxbinaca I fixed the problem. And add netrc feature to master branch. Please check out.

**Comment by vxbinaca** [comment]
```
vxbinaca@workstation/~/git/deviantart-gallery-downloader$ ruby with_login.rb "http://s-c.deviantart.com/gallery/"

/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- netrc (LoadError)
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from with_login.rb:2:in `<main>'
```

My machine name is "devinatart" in ~/.netrc, and the file permissions are correct (thats the two most common problems with netrc auth). So perhaps something on your end?

Edit: 

What gem are you using for netrc?

**Comment by vxbinaca** [comment]
Got it. Pull request coming.....

**Comment by vxbinaca** [comment]
Still going the under-ripping, it grabbed one more picture though from that account. And netrc works.

**Comment by xofred** [comment]
Sorry just saw the comment, i will check the gallery page problem again.

**Comment by xofred** [comment]
@vxbinaca Now should be fine ...

<img width="720" alt="2015-09-28 9 43 04" src="https://cloud.githubusercontent.com/assets/2174219/10137073/57449250-662a-11e5-9855-efe400bfddbd.png">

**Comment by xofred** [comment]
@Daiyousei Thanks for the fixing! Merged.

**Comment by vxbinaca** [comment]
Closing as .netrc and the under-rip bug are no longer an issue.
